
#Spring
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.apache=INFO
server.port=8080
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true
spring.security.oauth2.client.provider.spotify.userNameAttribute=email


#API
content.type =  application/x-www-form-urlencoded
base.package = com.recomsAI
auth.token   = https://accounts.spotify.com/api/token
album.endpoint = https://api.spotify.com/v1/albums/


