
#Spring
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.apache=INFO
server.port=8080
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true
spring.security.oauth2.client.provider.spotify.userNameAttribute=email


#Client
client.id = a390ec00bea44f9daf56ba8248e16dbb
client.secret = fbc8fca7f60f4f968dfddbcbfb937837
credential.type = client_credentials
content.type =  application/x-www-form-urlencoded
#API
base.package = com.recomsAI
auth.token   = https://accounts.spotify.com/api/token
album.endpoint = https://api.spotify.com/v1/albums/


